[package]
name = "domain-core"
version = "0.3.0"
authors = ["Martin Hoffmann <hn@nvnc.de>"]
description = "A DNS library for Rust – Core."
documentation = "https://docs.rs/domain-core/"
homepage = "https://github.com/nlnetlabs/domain-core"
repository = "https://github.com/nlnetlabs/domain-core"
readme = "README.md"
keywords = ["DNS", "domain"]
license = "MIT"

[lib]
name = "domain_core"
path = "src/lib.rs"

[dependencies]
bytes          = "0.4"
chrono         = "0.4"
rand           = "0.3"
failure        = "0.1"
failure_derive = "0.1"

