[package]
name    = "domain-rs"
version = "0.1.0"
authors = ["Martin Hoffmann <hn@nvnc.de>"]

[lib]
name = "domain"
path = "src/lib.rs"

[[bin]]
name = "dig"
path = "src/dig.rs"

[dependencies]
argparse = "0.2"

[dev-dependencies]
