[package]
name    = "domain"
version = "0.1.0"
authors = ["Martin Hoffmann <hn@nvnc.de>"]

[lib]
name = "domain"
path = "src/lib.rs"

[[example]]
name = "dig"
path = "examples/dig.rs"

[[example]]
name = "host"
path = "examples/host.rs"

[dependencies]
bytes       = "0.3"
rand        = "0.3"
rotor       = "0.6"
vecio       = "0.1"

[dev-dependencies]
argparse     = "0.2"
