[package]
name = "domain"
version = "0.5.0-pre"
edition = "2018"
authors = ["Martin Hoffmann <martin@nlnetlabs.nl>"]
description = "A DNS library for Rust – Meta Crate."
documentation = "https://docs.rs/domain"
homepage = "https://github.com/nlnetlabs/domain/"
repository = "https://github.com/nlnetlabs/domain/"
readme = "README.md"
keywords = ["DNS", "domain", "resolver", "futures"]
license = "BSD-3-Clause"

[lib]
name = "domain"
path = "src/lib.rs"

[dependencies]
chrono         = "0.4"
derive_more    = "0.99.1"
rand           = "0.7"
unwrap         = "1.2"
void           = "1.0"

bytes          = { version = "0.5", optional = true }
futures	       = { version = "0.1", optional = true }
openssl	       = { version = "0.10", optional = true }
ring           = { version = "0.16.11", optional = true }
smallvec       = { version = "1.2", optional = true }

[dependencies.tokio]
version = "0.1.19"
optional = true
default-features = false
features = ["io", "rt-full", "tcp", "udp"]

[dev-dependencies]
bytes = "0.5"
native-tls = "^0.2"
ring = "0.16.11"
tokio = { version = "0.1.19", default-features = false, features = ["io", "rt-full", "tcp", "udp"] }
tokio-tls = "^0.2"

[features]
default  = ["std"]
interop  = ["bytes", "ring"]
master   = ["std", "bytes"]
resolv   = ["std", "bytes", "futures", "smallvec", "tokio"]
sign     = ["std"]
std      = []
tsig     = ["bytes", "ring", "smallvec"]
validate = ["std", "ring"]
