[package]
name    = "domain-rs"
version = "0.1.0"
authors = ["Martin Hoffmann <hn@nvnc.de>"]

[lib]
name = "domain"
path = "src/lib.rs"

[[example]]
name = "dig"
path = "examples/dig.rs"

[dependencies]
rand     = "0.3"
rotor    = "0.6"
vecio    = "0.1"

[dev-dependencies]
argparse     = "0.2"
rotor        = "0.6"
rotor-stream = "0.6"
