[package]
name    = "domain-rs"
version = "0.1.0"
authors = ["Martin Hoffmann <hn@nvnc.de>"]

[lib]
name = "domain"
path = "src/lib.rs"

[[example]]
name = "dig"
path = "examples/dig.rs"

#[[example]]
#name = "reversed"
#path = "examples/reversed.rs"

[dependencies]
rand     = "0.3"
rotor    = { git = "https://github.com/partim/rotor.git", branch = "auto-shutdown" }
vecio    = "0.1"

[dev-dependencies]
argparse     = "0.2"
