[package]
name = "domain"
version = "0.4.1"
authors = ["Martin Hoffmann <hn@nvnc.de>"]
description = "A DNS library for Rust – Meta Crate."
documentation = "https://docs.rs/domain"
homepage = "https://github.com/nlnetlabs/domain/"
repository = "https://github.com/nlnetlabs/domain/"
readme = "README.md"
keywords = ["DNS", "domain", "resolver", "futures"]
license = "BSD-3-Clause"

[dependencies.domain-core]
path = "../domain-core"
version = "0.4.1"

[dependencies.domain-resolv]
path = "../domain-resolv"
version = "0.4.1"

